"""empty message

Revision ID: 9ea42ae5ee6e
Revises: 
Create Date: 2024-10-18 05:13:25.636144

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ea42ae5ee6e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carousel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image", sa.TEXT(), nullable=False),
        sa.Column("heading", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "newsletter",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "favourite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_unique_id", sa.VARCHAR(length=16), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_unique_id", name="unique_favorite"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.VARCHAR(length=16), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("display_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("size", sa.TEXT(), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.Column("keywords", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["category"], ["category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="unique_cart"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.CHAR(length=4), nullable=True),
        sa.Column("razorpay_order_id", sa.TEXT(), nullable=True),
        sa.Column("seen", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("Favourite")
    op.drop_table("Order")
    op.drop_table("ReturnRequest")
    op.drop_table("Product")
    op.drop_table("Newsletter")
    op.drop_table("Category")
    op.drop_table("Carousel")
    op.drop_table("Cart")
    op.drop_table("GiftCard")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("phone", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("phone")
        batch_op.drop_column("address")

    op.create_table(
        "GiftCard",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("price", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("used", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "Cart",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["Product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="unique_cart"),
    )
    op.create_table(
        "Carousel",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("image", sa.TEXT(), nullable=False),
        sa.Column("heading", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Category",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "Newsletter",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "Product",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("unique_id", sa.VARCHAR(length=16), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("display_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("stock", sa.INTEGER(), nullable=False),
        sa.Column("size", sa.TEXT(), nullable=False),
        sa.Column("category", sa.INTEGER(), nullable=False),
        sa.Column("keywords", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["category"], ["Category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ReturnRequest",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.INTEGER(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["Order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Order",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.CHAR(length=4), nullable=True),
        sa.Column("razorpay_order_id", sa.TEXT(), nullable=True),
        sa.Column("seen", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["Product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Favourite",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("product_unique_id", sa.VARCHAR(length=16), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_unique_id", name="unique_favorite"),
    )
    op.drop_table("order")
    op.drop_table("cart")
    op.drop_table("product")
    op.drop_table("favourite")
    op.drop_table("newsletter")
    op.drop_table("category")
    op.drop_table("carousel")
    # ### end Alembic commands ###
